# .github/workflows/workflow2.yml
name: Workflow 2 – Caller of Submodule Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # 第一个 Job：检出主仓库及其子模块
  checkout_submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository including submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

  # 第二个 Job：调用子模块中的可重用 Workflow，需要先完成检出
  call_workflow_from_submodule:
    needs: checkout_submodules
    # job-level uses 调用子模块里的 workflow1.yml
    uses: ./path_to_submodule/.github/workflows/workflow1.yml
    secrets:
      # 将主仓库的 test secret 传递给子模块 workflow_call
      test: ${{ secrets.test }}
